INSERT INTO DESCR  (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 1, 'ИД пакета', 10, 'PACKET_ID', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 2, 'Имя файла', 25, 'FILENAME', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('ANSWER', 2, 'Код запроса', 10, 'UNICODE', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 4, 'Отдел СП', 40, 'ORGAN', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 5, 'ФИО', 40, 'FIOISP', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('ANSWER', 3, 'Номер ИП', 15, 'NUMISP', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 6, 'Дата запроса', 10, 'DT', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 7, 'Исх. номер', 15, 'NUM', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 8, 'Физ./Юр.', 5, 'FIZUR', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 9, 'ФИО/Организация', 40, 'FIOORG', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 10, 'Дата рождения', 10, 'DATE_R', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 11, 'Адрес', 40, 'ADRESS', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 12, 'Пасспорт', 40, 'PASSPORT', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 13, 'Сумма долга', 10, 'SUMM', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 14, 'Обработан', 5, 'PROCESSED', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 15, 'ИД ответа', 10, 'ANSWERID', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 16, 'Дата загрузки', 10, 'DATELOAD', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('REQUESTS', 0, 'ИД записи', 10, 'PK', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('ANSWER', 0, 'ИД ответа', 10, 'PK', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('ANSWER', 1, 'ИД ответа', 10, 'ID_ZAPR', 1,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('ANSWER', 8, NULL, NULL, NULL, NULL,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('ANSWER', 4, NULL, NULL, 'DT', NULL,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('ANSWERS', 5, NULL, NULL, NULL, NULL,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('ANSWER', 6, NULL, NULL, NULL, NULL,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));
INSERT INTO DESCR (TABLENAME, FIELDORDER, DISPLAYNAME, DISPPLAYWIDTH, FIELDNAME, VISIBLE,pk)
                 VALUES ('ANSWER', 7, NULL, NULL, NULL, NULL,(SELECT GEN_ID(gen_descr_id, 1) FROM RDB$DATABASE));

COMMIT WORK;
